Repository Itstime-replog/Reflog-BE, pull requests merged in 2025-01, with the labels that each got.

#32 Feature : 주간/월간 분석 보고서 API 구현
  .github/workflows/github-actions.yml
  build.gradle
  docker-compose.yml
  src/main/java/itstime/reflog/ReflogApplication.java
  src/main/java/itstime/reflog/ai/dto/Message.java
  src/main/java/itstime/reflog/ai/dto/OpenAiRequest.java
  src/main/java/itstime/reflog/ai/dto/OpenAiResponse.java
  src/main/java/itstime/reflog/ai/service/OpenAiService.java
  src/main/java/itstime/reflog/analysis/controller/AnalysisController.java
  src/main/java/itstime/reflog/analysis/domain/AnalysisGoodBad.java
  src/main/java/itstime/reflog/analysis/domain/AnalysisStudyType.java
  src/main/java/itstime/reflog/analysis/domain/AnalysisUnderstandingAchievement.java
  src/main/java/itstime/reflog/analysis/domain/Improvement.java
  src/main/java/itstime/reflog/analysis/domain/WeeklyAnalysis.java
  src/main/java/itstime/reflog/analysis/domain/enums/GoodBad.java
  src/main/java/itstime/reflog/analysis/domain/enums/Period.java
  src/main/java/itstime/reflog/analysis/domain/enums/UnderstandingAchievement.java
  src/main/java/itstime/reflog/analysis/dto/AnalysisDto.java
  src/main/java/itstime/reflog/analysis/repository/AnalysisGoodBadRepository.java
  src/main/java/itstime/reflog/analysis/repository/AnalysisRepository.java
  src/main/java/itstime/reflog/analysis/repository/AnalysisStudyTypeRepository.java
  src/main/java/itstime/reflog/analysis/repository/AnalysisUnderstandingAchievementRepository.java
  src/main/java/itstime/reflog/analysis/repository/ImprovementRepository.java
  src/main/java/itstime/reflog/analysis/service/AnalysisCalculator.java
  src/main/java/itstime/reflog/analysis/service/AnalysisScheduler.java
  src/main/java/itstime/reflog/analysis/service/AnalysisService.java
  src/main/java/itstime/reflog/analysis/service/MonthlyAnalysisService.java
  src/main/java/itstime/reflog/analysis/service/PeriodFilter.java
  src/main/java/itstime/reflog/analysis/service/WeeklyAnalysisService.java
  src/main/java/itstime/reflog/config/OpenAiConfig.java
  src/main/java/itstime/reflog/todolist/service/TodolistService.java
  src/main/resources/application-prod.yml
Labels: :sparkles: Feature, ⚙ Setting

#37 Feature : 카테고리별 커뮤니티 게시물 조회 API
  src/main/java/itstime/reflog/community/controller/CommunityController.java
  src/main/java/itstime/reflog/community/domain/Community.java
  src/main/java/itstime/reflog/community/dto/CommunityDto.java
  src/main/java/itstime/reflog/community/repository/CommunityRepository.java
  src/main/java/itstime/reflog/community/service/CommunityService.java
  src/main/java/itstime/reflog/config/SecurityConfig.java
  src/main/java/itstime/reflog/mypage/repository/MyPageRepository.java
  src/main/java/itstime/reflog/retrospect/repository/RetrospectRepository.java
Labels: :sparkles: Feature

#44 Feature : 커뮤니티 검색 API 구현
  src/main/java/itstime/reflog/community/controller/CommunityController.java
  src/main/java/itstime/reflog/community/repository/CommunityRepository.java
  src/main/java/itstime/reflog/community/service/CommunityService.java
  src/main/java/itstime/reflog/retrospect/repository/RetrospectRepository.java
Labels: :sparkles: Feature

#45 Feature : 커뮤니티 댓글 API 구현
  src/main/java/itstime/reflog/comment/controller/CommentController.java
  src/main/java/itstime/reflog/comment/domain/Comment.java
  src/main/java/itstime/reflog/comment/dto/CommentDto.java
  src/main/java/itstime/reflog/comment/repository/CommentRepository.java
  src/main/java/itstime/reflog/comment/service/CommentService.java
  src/main/java/itstime/reflog/commentLike/domain/CommentLike.java
  src/main/java/itstime/reflog/commentLike/repository/CommentLikeRepository.java
  src/main/java/itstime/reflog/common/annotation/UserId.java
  src/main/java/itstime/reflog/common/code/status/ErrorStatus.java
  src/main/java/itstime/reflog/common/resolver/UserIdArgumentResolver.java
  src/main/java/itstime/reflog/community/controller/CommunityController.java
  src/main/java/itstime/reflog/community/domain/Community.java
  src/main/java/itstime/reflog/community/dto/CommunityDto.java
  src/main/java/itstime/reflog/community/service/CommunityService.java
  src/main/java/itstime/reflog/config/SecurityConfig.java
  src/main/java/itstime/reflog/config/WebConfig.java
  src/main/java/itstime/reflog/member/domain/Member.java
  src/main/java/itstime/reflog/schedule/controller/ScheduleController.java
  src/main/java/itstime/reflog/schedule/service/ScheduleService.java
Labels: :sparkles: Feature

#41 Feature : 커뮤니티 게시물 좋아요 API 구현
  src/main/java/itstime/reflog/common/code/status/ErrorStatus.java
  src/main/java/itstime/reflog/community/controller/CommunityController.java
  src/main/java/itstime/reflog/community/domain/Community.java
  src/main/java/itstime/reflog/community/dto/CommunityDto.java
  src/main/java/itstime/reflog/community/service/CommunityService.java
  src/main/java/itstime/reflog/member/domain/Member.java
  src/main/java/itstime/reflog/postlike/domain/PostLike.java
  src/main/java/itstime/reflog/postlike/domain/enums/PostType.java
  src/main/java/itstime/reflog/postlike/repository/PostLikeRepository.java
  src/main/java/itstime/reflog/postlike/service/PostLikeService.java
  src/main/java/itstime/reflog/retrospect/domain/Retrospect.java
Labels: :sparkles: Feature

#53 [FEAT] : 댓글 리펙토링
  src/main/java/itstime/reflog/comment/controller/CommentController.java
  src/main/java/itstime/reflog/comment/domain/Comment.java
  src/main/java/itstime/reflog/comment/dto/CommentDto.java
  src/main/java/itstime/reflog/comment/service/CommentService.java
  src/main/java/itstime/reflog/common/code/status/ErrorStatus.java
Labels: 🔨Refactor

#49 Fix: 레디스 토큰 저장 오류 수정
  .github/workflows/github-actions.yml
  docker-compose.yml
  src/main/resources/application-prod.yml
Labels: 🐞BugFix

#55 Feat : 로그인 리펙토링
  src/main/java/itstime/reflog/analysis/controller/AnalysisController.java
  src/main/java/itstime/reflog/analysis/service/MonthlyAnalysisService.java
  src/main/java/itstime/reflog/analysis/service/WeeklyAnalysisService.java
  src/main/java/itstime/reflog/comment/service/CommentService.java
  src/main/java/itstime/reflog/community/controller/CommunityController.java
  src/main/java/itstime/reflog/community/service/CommunityService.java
  src/main/java/itstime/reflog/goal/controller/DailyGoalController.java
  src/main/java/itstime/reflog/goal/service/DailyGoalService.java
  src/main/java/itstime/reflog/member/service/MemberServiceHelper.java
  src/main/java/itstime/reflog/mypage/controller/MyPageController.java
  src/main/java/itstime/reflog/mypage/service/MyPageService.java
  src/main/java/itstime/reflog/postlike/service/PostLikeService.java
  src/main/java/itstime/reflog/retrospect/controller/RetrospectController.java
  src/main/java/itstime/reflog/retrospect/service/RetrospectService.java
  src/main/java/itstime/reflog/schedule/controller/ScheduleController.java
  src/main/java/itstime/reflog/schedule/service/ScheduleService.java
  src/main/java/itstime/reflog/todolist/controller/TodolistController.java
  src/main/java/itstime/reflog/todolist/service/TodolistService.java
Labels: 🔨Refactor

#57 Feat : 로그아웃, 회원탈퇴 구현
  src/main/java/itstime/reflog/member/controller/MemberController.java
  src/main/java/itstime/reflog/member/service/MemberService.java
  src/main/java/itstime/reflog/util/JwtUtil.java
Labels: :sparkles: Feature

#62 Feature: 인기글 조회 API 구현
  src/main/java/itstime/reflog/common/code/status/ErrorStatus.java
  src/main/java/itstime/reflog/community/controller/CommunityController.java
  src/main/java/itstime/reflog/config/RedisConfig.java
  src/main/java/itstime/reflog/postlike/domain/PopularPost.java
  src/main/java/itstime/reflog/postlike/repository/PopularPostRepository.java
  src/main/java/itstime/reflog/postlike/repository/PostLikeRepository.java
  src/main/java/itstime/reflog/postlike/service/PopularScheduler.java
  src/main/java/itstime/reflog/postlike/service/PostLikeService.java
Labels: :sparkles: Feature

#65 Feat : 미션&배지 API 구현
  src/main/java/itstime/reflog/analysis/service/MonthlyAnalysisService.java
  src/main/java/itstime/reflog/analysis/service/WeeklyAnalysisService.java
  src/main/java/itstime/reflog/comment/service/CommentService.java
  src/main/java/itstime/reflog/community/service/CommunityService.java
  src/main/java/itstime/reflog/mission/domain/Badge.java
  src/main/java/itstime/reflog/mission/domain/UserMission.java
  src/main/java/itstime/reflog/mission/repository/UserBadgeRepository.java
  src/main/java/itstime/reflog/mission/repository/UserMissionRepository.java
  src/main/java/itstime/reflog/mission/service/BadgeService.java
  src/main/java/itstime/reflog/mission/service/MissionService.java
  src/main/java/itstime/reflog/mypage/controller/MyPageController.java
  src/main/java/itstime/reflog/mypage/dto/MyPageDto.java
  src/main/java/itstime/reflog/mypage/service/MyPageService.java
  src/main/java/itstime/reflog/postlike/service/PostLikeService.java
  src/main/java/itstime/reflog/retrospect/controller/RetrospectController.java
  src/main/java/itstime/reflog/retrospect/service/RetrospectService.java
  src/main/java/itstime/reflog/todolist/controller/TodolistController.java
  src/main/java/itstime/reflog/todolist/service/TodolistService.java
Labels: :sparkles: Feature

#67 refactor : 닉네임&이메일 중복 처리
  src/main/java/itstime/reflog/common/code/status/ErrorStatus.java
  src/main/java/itstime/reflog/mypage/repository/MyPageRepository.java
  src/main/java/itstime/reflog/mypage/service/MyPageService.java
Labels: 🔨Refactor

#70 Feat : 알림 API 구현
  src/main/java/itstime/reflog/analysis/service/MonthlyAnalysisService.java
  src/main/java/itstime/reflog/analysis/service/WeeklyAnalysisService.java
  src/main/java/itstime/reflog/comment/service/CommentService.java
  src/main/java/itstime/reflog/common/code/status/ErrorStatus.java
  src/main/java/itstime/reflog/config/SchedulingConfig.java
  src/main/java/itstime/reflog/mission/domain/Badge.java
  src/main/java/itstime/reflog/mission/service/BadgeService.java
  src/main/java/itstime/reflog/mission/service/MissionService.java
  src/main/java/itstime/reflog/mypage/controller/NotificationSettingsController.java
  src/main/java/itstime/reflog/mypage/domain/NotificationSettings.java
  src/main/java/itstime/reflog/mypage/dto/NotificationSettingsDto.java
  src/main/java/itstime/reflog/mypage/repository/NotificationSettingsRepository.java
  src/main/java/itstime/reflog/mypage/service/NotificationSettingsService.java
  src/main/java/itstime/reflog/notification/controller/NotificationController.java
  src/main/java/itstime/reflog/notification/domain/Notification.java
  src/main/java/itstime/reflog/notification/domain/NotificationType.java
  src/main/java/itstime/reflog/notification/dto/NotificationDto.java
  src/main/java/itstime/reflog/notification/repository/NotificationRepository.java
  src/main/java/itstime/reflog/notification/service/NotificationService.java
  src/main/java/itstime/reflog/postlike/service/PostLikeService.java
  src/main/java/itstime/reflog/schedule/controller/ScheduleController.java
  src/main/java/itstime/reflog/schedule/domain/Schedule.java
  src/main/java/itstime/reflog/schedule/dto/ScheduleDto.java
  src/main/java/itstime/reflog/schedule/service/ScheduleService.java
Labels: :sparkles: Feature

#69 Feature : 북마크 API 구현
  src/main/java/itstime/reflog/common/code/status/ErrorStatus.java
  src/main/java/itstime/reflog/community/controller/CommunityController.java
  src/main/java/itstime/reflog/community/dto/CommunityDto.java
  src/main/java/itstime/reflog/community/service/CommunityService.java
  src/main/java/itstime/reflog/postlike/domain/PostLike.java
  src/main/java/itstime/reflog/postlike/domain/enums/LikeType.java
  src/main/java/itstime/reflog/postlike/dto/PostLikeDto.java
  src/main/java/itstime/reflog/postlike/repository/PostLikeRepository.java
  src/main/java/itstime/reflog/postlike/service/PostLikeService.java
Labels: :sparkles: Feature, 🔨Refactor

#75 Modify: 커뮤니티 조회 API 커뮤니티 글 id 데이터 추가
  src/main/java/itstime/reflog/community/dto/CommunityDto.java
Labels: 🔧Modify

#79 Refactor : 인기글 조회 API 리팩토링
  src/main/java/itstime/reflog/postlike/domain/PopularPost.java
  src/main/java/itstime/reflog/postlike/domain/PostLike.java
  src/main/java/itstime/reflog/postlike/repository/PopularPostRepository.java
  src/main/java/itstime/reflog/postlike/repository/PostLikeRepository.java
  src/main/java/itstime/reflog/postlike/service/PopularScheduler.java
  src/main/java/itstime/reflog/postlike/service/PostLikeService.java
Labels: 🔨Refactor

#73 Feat: nginx, https 배포
  docker-compose.yml
Labels: 🌏 Deploy

#81 Fix: app컨테이너 실행 안됨 오류
  .github/workflows/github-actions.yml
  docker-compose.yml
  src/main/java/itstime/reflog/config/SwaggerConfig.java
Labels: 🌏 Deploy, 🐞BugFix

#82 Refactor : 커뮤니티 조회 API 리팩토링
  src/main/java/itstime/reflog/community/domain/Community.java
  src/main/java/itstime/reflog/community/dto/CommunityDto.java
  src/main/java/itstime/reflog/community/repository/CommunityRepository.java
  src/main/java/itstime/reflog/community/service/CommunityConverter.java
  src/main/java/itstime/reflog/community/service/CommunityService.java
  src/main/java/itstime/reflog/mypage/dto/MyPageDto.java
  src/main/java/itstime/reflog/mypage/service/MyPageService.java
  src/main/java/itstime/reflog/postlike/service/PostLikeService.java
Labels: 🔨Refactor
